version: '3.0'

services:
  mongo:
    image: mongo:6.0.3
    restart: always
    ports:
      - '27017:27017'
    container_name: erp-db
    volumes:
      - ./mongodb:/var/lib/mongodb/data
  mongoexpress:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - '8082:8081'
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
